version: '3.9'

# Network
networks:
  web_network:
    name: react_mui_strapi_network
    driver: bridge

# Services
services:

  # React App Development
  react_dev:
    build: 
      context: ./reactapp
      dockerfile: Dockerfile.dev
    container_name: reactmui_dev
    restart: always
    volumes:
      - ./reactapp:/usr/app
      - /usr/app/node_modules  # Bookmarks Volume
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network

  # React App Production
  react_prod:
    build: 
      context: ./reactapp
      dockerfile: Dockerfile.prod
    container_name: reactmui_prod
    restart: always
    ports:
      - 4173:4173
    networks:
      - web_network

  # Nginx Web Server
  nginx:
    image: nginx:latest
    container_name: nginx_reactmui
    restart: always
    ports:
      - 8800:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react_prod
    networks:
      - web_network

  # MySQL Database
  mysqldb:
    image: mysql:8.0.26
    container_name: mysql_reactmui
    restart: always
    ports:
      - 4406:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    volumes:
      - ./mysqldb:/var/lib/mysql
    networks:
      - web_network

  # Strapi CMS
  strapi:
    container_name: strapi_reactmui
    build: ./strapiapp
    image: mystrapi:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 1337:1337
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: mysqldb
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./strapiapp/config:/opt/app/config
      - ./strapiapp/src:/opt/app/src
      - ./strapiapp/package.json:/opt/package.json
      - ./strapiapp/.env:/opt/app/.env
    depends_on:
      - mysqldb
    networks:
      - web_network